import Phaser from 'phaser';
import charList from '../../public/assets/pixel/chars.json';
import fontXml from '../../public/assets/pixel/font.xml?raw';
import fontPng from '../../public/assets/pixel/font.png?inline';
import propsMeta from '../../public/assets/pixel/props.json';
import propsPng from '../../public/assets/pixel/props.png?inline';
import tileIndex from '../../public/assets/pixel/tiles.json';
import tilesPng from '../../public/assets/pixel/tiles.png?inline';
import uiMeta from '../../public/assets/pixel/ui.json';
import uiPng from '../../public/assets/pixel/ui.png?inline';
import { CHAR_H, CHAR_W, FONT, TILE } from './config';
import type { PropIndex, TileIndex } from './maps/compile';

/*
 * All of the pixel game's art is generated by tools/pixel/build.py and inlined into the bundle as data
 * URLs (it is only a few kilobytes), so the game is a single self-contained page.
 * Anything in public/assets/override/pixel/ with the same path wins, in dev builds.
 */
const CHAR_PNGS = import.meta.glob('../../public/assets/pixel/chars/*.png', { query: '?inline', import: 'default', eager: true }) as Record<string, string>;
const PORTRAIT_PNGS = import.meta.glob('../../public/assets/pixel/portraits/*.png', { query: '?inline', import: 'default', eager: true }) as Record<string, string>;

export const TILES = tileIndex as TileIndex;
export const PROPS = propsMeta as unknown as PropIndex;
export const UI = uiMeta as Record<string, { x: number; y: number; w: number; h: number }>;
export const CHARS = charList as string[];

const byName = (glob: Record<string, string>) =>
  Object.fromEntries(Object.entries(glob).map(([path, url]) => [path.split('/').pop()!.replace('.png', ''), url]));

export function preloadPixelArt(load: Phaser.Loader.LoaderPlugin): void {
  load.spritesheet('tiles', tilesPng, { frameWidth: TILE, frameHeight: TILE });
  load.image('props', propsPng);
  load.image('ui', uiPng);
  load.image('font-png', fontPng);
  for (const [id, url] of Object.entries(byName(CHAR_PNGS))) load.spritesheet(`char-${id}`, url, { frameWidth: CHAR_W, frameHeight: CHAR_H });
  for (const [id, url] of Object.entries(byName(PORTRAIT_PNGS))) load.image(`portrait-${id}`, url);
}

/** After loading: named frames for props and UI pieces, the bitmap font, and walk animations. */
export function registerPixelArt(scene: Phaser.Scene): void {
  const tex = scene.textures;
  const props = tex.get('props');
  for (const [k, r] of Object.entries(PROPS)) props.add(k, 0, r.x, r.y, r.w, r.h);
  const ui = tex.get('ui');
  for (const [k, r] of Object.entries(UI)) ui.add(k, 0, r.x, r.y, r.w, r.h);

  const xml = new DOMParser().parseFromString(fontXml, 'text/xml');
  const fontTex = tex.get('font-png');
  const data = Phaser.GameObjects.BitmapText.ParseXMLBitmapFont(xml, fontTex.get());
  scene.cache.bitmapFont.add(FONT, { data, texture: 'font-png', frame: null });

  const dirs = ['down', 'up', 'left', 'right'];
  for (const id of CHARS) {
    const key = `char-${id}`;
    if (!tex.exists(key)) continue;
    dirs.forEach((d, row) => {
      const animKey = `${id}-walk-${d}`;
      if (!scene.anims.exists(animKey)) {
        scene.anims.create({ key: animKey, frames: scene.anims.generateFrameNumbers(key, { frames: [row * 3 + 1, row * 3, row * 3 + 2, row * 3] }), frameRate: 8, repeat: -1 });
      }
    });
  }
  // A soft ground shadow for people.
  if (!tex.exists('shadow')) {
    const g = scene.make.graphics({}, false);
    g.fillStyle(0x1a1c2c, 0.18).fillEllipse(8, 3, 16, 6).fillStyle(0x1a1c2c, 0.22).fillEllipse(8, 3, 12, 4);
    g.generateTexture('shadow', 16, 6);
    g.destroy();
  }
  // Cloud shadows: a few soft blobs drawn once into a texture.
  if (!tex.exists('cloud')) {
    const cv = document.createElement('canvas');
    cv.width = 256; cv.height = 128;
    const cx = cv.getContext('2d')!;
    for (const [x, y, r] of [[70, 64, 50], [120, 50, 56], [170, 70, 46], [110, 84, 40], [200, 58, 34]] as const) {
      const gr = cx.createRadialGradient(x, y, 0, x, y, r);
      gr.addColorStop(0, 'rgba(40,46,80,0.5)');
      gr.addColorStop(1, 'rgba(40,46,80,0)');
      cx.fillStyle = gr;
      cx.fillRect(0, 0, 256, 128);
    }
    tex.addCanvas('cloud', cv);
  }
  // Morning light: warm from the top left, fading across the screen.
  if (!tex.exists('sun')) {
    const cv = document.createElement('canvas');
    cv.width = 240; cv.height = 135;
    const cx = cv.getContext('2d')!;
    const gr = cx.createRadialGradient(0, 0, 10, 0, 0, 260);
    gr.addColorStop(0, 'rgba(255,214,150,0.55)');
    gr.addColorStop(0.5, 'rgba(255,200,140,0.18)');
    gr.addColorStop(1, 'rgba(255,200,140,0)');
    cx.fillStyle = gr;
    cx.fillRect(0, 0, 240, 135);
    tex.addCanvas('sun', cv);
  }
  // A 2x2 petal for the falling copper-pod flowers.
  if (!tex.exists('petal')) {
    const g = scene.make.graphics({}, false);
    g.fillStyle(0xf6c63c).fillRect(0, 0, 2, 2).fillStyle(0xe09a24).fillRect(1, 1, 1, 1);
    g.generateTexture('petal', 2, 2);
    g.destroy();
  }
}

/** Advance widths of the bitmap font, for word wrapping and centring. */
export function glyphWidths(scene: Phaser.Scene): (ch: string) => number {
  const data = scene.cache.bitmapFont.get(FONT).data as { chars: Record<number, { xAdvance: number }> };
  return (ch: string) => data.chars[ch.charCodeAt(0)]?.xAdvance ?? 4;
}
